version: '3.3'

services:
   slapd:
      volumes:
         - /etc/localtime:/etc/localtime
         - /var/local/dcm4chee-arc/ldap:/var/lib/ldap
         - /var/local/dcm4chee-arc/slapd.d:/etc/ldap/slapd.d
      ports:
         - "389:389"
   postgres:
      volumes:
         - /etc/localtime:/etc/localtime
         - /var/local/dcm4chee-arc/db:/var/lib/postgresql/data
      environment:
         - POSTGRES_DB=pacsdb
         - POSTGRES_USER=pacs
         - POSTGRES_PASSWORD=pacs
      ports:
         - "5432:5432"
   dcm4chee-arc:
      volumes:
         - /var/local/dcm4chee-arc/wildfly:/opt/wildfly/standalone
         - /var/local/dcm4chee-arc/storage:/storage
      ports:
         - "9090:8080"
         - "9990:9990"
         - "11112:11112"
         - "2575:2575"
   dcmrs-broker:
      environment:
         - QIDO_REMOTE_AE=DCM4CHEE
         - QIDO_REMOTE_HOST=<your host>
         - QIDO_REMOTE_PORT=11112
         - QIDO_LOCAL_AE=QIDO-TESTING
         - WAD0_REMOTE_AE=DCM4CHEE
         - WADO_REMOTE_HOST=<your host>
         - WADO_REMOTE_PORT=11112
         - WADO_LOCAL_AE=WADO-TESTING
         - SCP_LOCAL_AE=PACS-SCP
         - SCP_CACHE_DIR_PATH=/dcmrs-broker/cache
      volumes:
         - /var/local/dcmrs-broker/cache:/dcmrs-broker/cache
      ports:
         - "4567:4567"
         - "11122:11112"
   token-introspector:
      ports:
         - "9004:5000"
   s4s-fhir-broker:
      environment:
         - DICOM_RS_BROKER_QIDO_URL=http://<dicomrs broker host>:4567/qido-rs
         - DICOM_RS_BROKER_WADO_URL=http://<dicomrs broker host>:4567/wado-rs
         - INTROSPECTION_SERVICE_URL=http://<introspection service host>:9004/api/introspect
      ports:
         - "8080:8080"