version: '3.3'

services:
   slapd:
      image: dcm4che/slapd-dcm4chee:2.4.44-10.5
      expose:
         - "389"
      networks:
         - internal
   postgres:
      image: dcm4che/postgres-dcm4chee:9.6-10
      expose:
         - "5432"
      networks:
         - internal
   dcm4chee-arc:
      image: dcm4che/dcm4chee-arc-psql:5.10.5
      expose:
         - "8080"
         - "9990"
         - "11112"
         - "2575"
      links:
         - slapd:ldap
         - postgres:db
      networks:
         - internal
   dcmrs-broker:
      build:
         context: ./dcmrs-broker
         dockerfile: Dockerfile
      image: rsna/dcmrs-broker
      expose:
         - "4567"
         - "11112"
      networks:
         - internal
   introspection-service:
      build:
         context: ./token-introspector
         dockerfile: Dockerfile
      image: rsna/introspection-service
      expose:
         - "5000"
      networks:
         - internal         
   s4s-fhir-broker:
      build:
         context: ./s4s-fhir-broker/hapi-fhir-jpaserver-example
         dockerfile: Dockerfile
      image: rsna/s4s-fhir-broker
      expose:
         - "8080"
      networks:
         - internal
   rsnadb:
      build:
         context: ./s4s-edgeserverdb
         dockerfile: Dockerfile
      image: rsna/s4s-edgeserverdb
      expose:
         - "5432"
      networks:
         - internal
networks:
   internal:
      driver: bridge
